"""Initial migration

Revision ID: 2f222905f433
Revises: 
Create Date: 2026-02-03 21:20:23.712007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f222905f433'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('__EFMigrationsHistory')
    op.drop_index(op.f('idx_failed_messages_created_at_utc'), table_name='failed_messages')
    op.drop_index(op.f('idx_failed_messages_status_cd'), table_name='failed_messages')
    op.drop_index(op.f('idx_failed_messages_topic_cd'), table_name='failed_messages')
    op.drop_table('failed_messages')
    op.alter_column('oauth_tokens', 'access_token_txt',
               existing_type=sa.TEXT(),
               type_=sa.String(length=4096),
               existing_nullable=False)
    op.alter_column('oauth_tokens', 'refresh_token_txt',
               existing_type=sa.TEXT(),
               type_=sa.String(length=4096),
               nullable=True)
    op.alter_column('oauth_tokens', 'expires_at_utc',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('oauth_tokens', 'created_at_utc',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('oauth_tokens', 'modified_at_utc',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_unique_constraint(None, 'oauth_tokens', ['user_mail_account_id'])
    op.create_foreign_key(None, 'oauth_tokens', 'user_mail_accounts', ['user_mail_account_id'], ['user_mail_account_id'])
    op.alter_column('user_mail_accounts', 'email_address_txt',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('user_mail_accounts', 'created_at_utc',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('user_mail_accounts', 'modified_at_utc',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_unique_constraint(None, 'user_mail_accounts', ['email_address_txt'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_mail_accounts', type_='unique')
    op.alter_column('user_mail_accounts', 'modified_at_utc',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('user_mail_accounts', 'created_at_utc',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('user_mail_accounts', 'email_address_txt',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'oauth_tokens', type_='foreignkey')
    op.drop_constraint(None, 'oauth_tokens', type_='unique')
    op.alter_column('oauth_tokens', 'modified_at_utc',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('oauth_tokens', 'created_at_utc',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('oauth_tokens', 'expires_at_utc',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('oauth_tokens', 'refresh_token_txt',
               existing_type=sa.String(length=4096),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('oauth_tokens', 'access_token_txt',
               existing_type=sa.String(length=4096),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_table('failed_messages',
    sa.Column('failed_message_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('message_id_txt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('topic_cd', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('subscription_txt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('error_message_txt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('error_stack_trace_txt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('failed_at_utc', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('status_cd', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('retry_count_no', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('resolved_at_utc', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('message_content_txt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at_utc', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('modified_at_utc', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('failed_message_id', name=op.f('PK_failed_messages'))
    )
    op.create_index(op.f('idx_failed_messages_topic_cd'), 'failed_messages', ['topic_cd'], unique=False)
    op.create_index(op.f('idx_failed_messages_status_cd'), 'failed_messages', ['status_cd'], unique=False)
    op.create_index(op.f('idx_failed_messages_created_at_utc'), 'failed_messages', ['created_at_utc'], unique=False)
    op.create_table('__EFMigrationsHistory',
    sa.Column('MigrationId', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('ProductVersion', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('MigrationId', name=op.f('PK___EFMigrationsHistory'))
    )
    # ### end Alembic commands ###
